name: CI

on:
  push:
    branches:
      - main
  pull_request: {}

runs-on: ubuntu-latest

jobs:
  ci:
    - uses: actions/checkout@v5
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.19'
    - name: Run CI checks
      run: 'make ci'
